// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_lYItm7wr6sQzpTFZ5qmdaAJSy0FpRMM',
    appId: '1:787200647060:web:0845af94f72b48aa6db981',
    messagingSenderId: '787200647060',
    projectId: 'elearning-ae8a2',
    authDomain: 'elearning-ae8a2.firebaseapp.com',
    storageBucket: 'elearning-ae8a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPaIHoVqUTDtiQynCOG7OFsZ3IatRTy5g',
    appId: '1:787200647060:android:8c4200260c9863e26db981',
    messagingSenderId: '787200647060',
    projectId: 'elearning-ae8a2',
    storageBucket: 'elearning-ae8a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3aJDq195_PWrBvqQJaDxjJSljQJNH124',
    appId: '1:787200647060:ios:2324981b56399e5d6db981',
    messagingSenderId: '787200647060',
    projectId: 'elearning-ae8a2',
    storageBucket: 'elearning-ae8a2.appspot.com',
    androidClientId: '787200647060-ru7246cf54uontuc0462qbm3bv20tacu.apps.googleusercontent.com',
    iosClientId: '787200647060-v6n49idd4ldrnjo1bilue5mu0a6dcpm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.edspertFlutterFinalProjectElearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3aJDq195_PWrBvqQJaDxjJSljQJNH124',
    appId: '1:787200647060:ios:8221a23c525da4596db981',
    messagingSenderId: '787200647060',
    projectId: 'elearning-ae8a2',
    storageBucket: 'elearning-ae8a2.appspot.com',
    androidClientId: '787200647060-ru7246cf54uontuc0462qbm3bv20tacu.apps.googleusercontent.com',
    iosClientId: '787200647060-85og6pa3uv2vfp26fks0nf4dgk4957t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.edspertFlutterFinalProjectElearning.RunnerTests',
  );
}
